# Generated by Django 4.0.4 on 2022-06-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schools',
        ),
    ]
